--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1 (Debian 12.1-1.pgdg100+1)
-- Dumped by pg_dump version 12.1 (Debian 12.1-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ageoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ageoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer NOT NULL,
    criteria_no integer NOT NULL,
    no integer
);


ALTER TABLE public.ageoption OWNER TO postgres;

--
-- Name: ageoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ageoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ageoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: criteria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.criteria (
    id integer NOT NULL,
    criteria_no integer NOT NULL,
    criteria_title character varying NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.criteria OWNER TO postgres;

--
-- Name: criteria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.criteria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.criteria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eduoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eduoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.eduoption OWNER TO postgres;

--
-- Name: eduoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eduoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eduoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forgotpasswordquestionoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forgotpasswordquestionoption (
    id integer NOT NULL,
    title character varying NOT NULL
);


ALTER TABLE public.forgotpasswordquestionoption OWNER TO postgres;

--
-- Name: forgotpasswordquestionoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forgotpasswordquestionoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forgotpasswordquestionoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: frechangenameoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.frechangenameoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.frechangenameoption OWNER TO postgres;

--
-- Name: frechangenameoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.frechangenameoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.frechangenameoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcallow; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcallow (
    id integer NOT NULL,
    funcno integer NOT NULL,
    title character varying NOT NULL,
    superadminallow boolean DEFAULT true,
    adminallow boolean DEFAULT true,
    employeeallow boolean DEFAULT true,
    loanerallow boolean DEFAULT true
);


ALTER TABLE public.funcallow OWNER TO postgres;

--
-- Name: funcallow_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funcallow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcallow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genderstatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genderstatus (
    id integer NOT NULL,
    title character varying
);


ALTER TABLE public.genderstatus OWNER TO postgres;

--
-- Name: geography; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.geography (
    id integer NOT NULL,
    title character varying
);


ALTER TABLE public.geography OWNER TO postgres;

--
-- Name: haveguarantoroption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.haveguarantoroption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.haveguarantoroption OWNER TO postgres;

--
-- Name: haveguarantoroption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.haveguarantoroption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.haveguarantoroption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: iamguarantoroption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.iamguarantoroption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.iamguarantoroption OWNER TO postgres;

--
-- Name: iamguarantoroption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.iamguarantoroption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iamguarantoroption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incomeperdebtoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incomeperdebtoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.incomeperdebtoption OWNER TO postgres;

--
-- Name: incomeperdebtoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incomeperdebtoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incomeperdebtoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incometrendoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incometrendoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.incometrendoption OWNER TO postgres;

--
-- Name: incometrendoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incometrendoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incometrendoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: joboption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.joboption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.joboption OWNER TO postgres;

--
-- Name: joboption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.joboption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.joboption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loanobjectoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loanobjectoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.loanobjectoption OWNER TO postgres;

--
-- Name: loanobjectoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loanobjectoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loanobjectoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id integer NOT NULL,
    subdistrict character varying NOT NULL,
    district character varying NOT NULL,
    zipcode character varying NOT NULL,
    subdistrict_code character varying NOT NULL,
    district_code character varying NOT NULL,
    province_code character varying NOT NULL
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: marriedstatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marriedstatus (
    id integer NOT NULL,
    title character varying
);


ALTER TABLE public.marriedstatus OWNER TO postgres;

--
-- Name: mortgagesecuritiesperloanoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mortgagesecuritiesperloanoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.mortgagesecuritiesperloanoption OWNER TO postgres;

--
-- Name: mortgagesecuritiesperloanoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mortgagesecuritiesperloanoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mortgagesecuritiesperloanoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paydebthistoryoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paydebthistoryoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.paydebthistoryoption OWNER TO postgres;

--
-- Name: paydebthistoryoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.paydebthistoryoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paydebthistoryoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissionaccess; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissionaccess (
    id integer NOT NULL,
    accessshowloanernewlistadmin boolean NOT NULL,
    accessshowloanernewlistworker boolean NOT NULL,
    accessshowloanerinverifylistadmin boolean NOT NULL,
    accessshowloanerinverifylistworker boolean NOT NULL,
    accessshowloanerwaitapprovelistadmin boolean NOT NULL,
    accessshowloanerwaitapprovelistworker boolean NOT NULL,
    verifyquestionnairebyadmin boolean NOT NULL,
    verifyquestionnairebyworker boolean NOT NULL,
    sendtoapprovebyadmin boolean NOT NULL,
    sendtoapprovebyworker boolean NOT NULL,
    accessshowloanerhadapprovelistadmin boolean,
    accessshowloanerhadapprovelistworker boolean,
    accessshowloanerhaddenylistadmin boolean,
    accessshowloanerhaddenylistworker boolean,
    accessshowloanernotmakelistadmin boolean,
    accessshowloanernotmakelistworker boolean
);


ALTER TABLE public.permissionaccess OWNER TO postgres;

--
-- Name: provinces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.provinces (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    title_en character varying,
    score integer,
    geographyid integer
);


ALTER TABLE public.provinces OWNER TO postgres;

--
-- Name: provinces_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.provinces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provinces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questionnaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaire (
    id bigint NOT NULL,
    loanerid bigint NOT NULL,
    updatedby bigint,
    approveby bigint,
    statusid integer NOT NULL,
    sendat timestamp with time zone,
    updatedat timestamp with time zone,
    approverate double precision,
    approvetotal double precision,
    interest double precision,
    verifycomment character varying,
    approvecomment character varying,
    creditgrade character varying,
    creditrisk character varying,
    risklevel character varying,
    matrixindex character varying,
    suggest character varying DEFAULT ''::character varying NOT NULL,
    suggestscore integer,
    suggestgivescore integer,
    income double precision NOT NULL,
    loan double precision NOT NULL,
    debtpermonth double precision NOT NULL,
    totaldebt double precision NOT NULL,
    saving double precision NOT NULL,
    mortgagesecurities double precision NOT NULL,
    age character varying NOT NULL,
    job character varying NOT NULL,
    edu character varying NOT NULL,
    timejob character varying NOT NULL,
    frechangename character varying NOT NULL,
    timeofphonenumber character varying NOT NULL,
    timeofnameinhouseparticular character varying NOT NULL,
    paydebthistory character varying NOT NULL,
    statusinhouseparticular character varying NOT NULL,
    incomeperdebt character varying NOT NULL,
    totaldebtperyearincome character varying NOT NULL,
    savingperloan character varying NOT NULL,
    mortgagesecuritiesperloan character varying NOT NULL,
    haveguarantor character varying NOT NULL,
    iamguarantor character varying NOT NULL,
    incometrend character varying NOT NULL,
    loanobject character varying NOT NULL,
    provincecode character varying NOT NULL,
    incomew double precision NOT NULL,
    loanw double precision NOT NULL,
    debtpermonthw double precision NOT NULL,
    totaldebtw double precision NOT NULL,
    savingw double precision NOT NULL,
    mortgagesecuritiesw double precision NOT NULL,
    agew character varying NOT NULL,
    jobw character varying NOT NULL,
    eduw character varying NOT NULL,
    timejobw character varying NOT NULL,
    frechangenamew character varying NOT NULL,
    timeofphonenumberw character varying NOT NULL,
    timeofnameinhouseparticularw character varying NOT NULL,
    paydebthistoryw character varying NOT NULL,
    statusinhouseparticularw character varying NOT NULL,
    incomeperdebtw character varying NOT NULL,
    totaldebtperyearincomew character varying NOT NULL,
    savingperloanw character varying NOT NULL,
    mortgagesecuritiesperloanw character varying NOT NULL,
    haveguarantorw character varying NOT NULL,
    iamguarantorw character varying NOT NULL,
    incometrendw character varying NOT NULL,
    loanobjectw character varying NOT NULL,
    provincecodew character varying NOT NULL,
    loanerpayback double precision,
    suggestw character varying DEFAULT ''::character varying,
    changeresultcomment character varying
);


ALTER TABLE public.questionnaire OWNER TO postgres;

--
-- Name: questionnaire_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questionnaire ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaire_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questionnairestatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnairestatus (
    id integer NOT NULL,
    title character varying
);


ALTER TABLE public.questionnairestatus OWNER TO postgres;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    title character varying NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: savingperloanoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.savingperloanoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.savingperloanoption OWNER TO postgres;

--
-- Name: savingperloanoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.savingperloanoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.savingperloanoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statusinhouseparticularoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statusinhouseparticularoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.statusinhouseparticularoption OWNER TO postgres;

--
-- Name: statusinhouseparticularoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.statusinhouseparticularoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statusinhouseparticularoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timejoboption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timejoboption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.timejoboption OWNER TO postgres;

--
-- Name: timejoboption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timejoboption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timejoboption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeofnameinhouseparticularoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timeofnameinhouseparticularoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.timeofnameinhouseparticularoption OWNER TO postgres;

--
-- Name: timeofnameinhouseparticularoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timeofnameinhouseparticularoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeofnameinhouseparticularoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeofphonenumberoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timeofphonenumberoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.timeofphonenumberoption OWNER TO postgres;

--
-- Name: timeofphonenumberoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timeofphonenumberoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeofphonenumberoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: totaldebtperyearincomeoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.totaldebtperyearincomeoption (
    id integer NOT NULL,
    code character varying NOT NULL,
    title character varying NOT NULL,
    score integer,
    criteria_no integer NOT NULL
);


ALTER TABLE public.totaldebtperyearincomeoption OWNER TO postgres;

--
-- Name: totaldebtperyearincomeoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.totaldebtperyearincomeoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.totaldebtperyearincomeoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    roleid integer,
    citizenid character varying,
    email character varying NOT NULL,
    password character varying NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    genderid integer,
    marriedid integer,
    religion character varying,
    birthday character varying NOT NULL,
    phone character varying NOT NULL,
    child integer,
    facebook character varying,
    ig character varying,
    line character varying,
    address1_home character varying,
    address2_home character varying,
    subdistrict_home character varying,
    district_home character varying,
    provincecode_home character varying,
    zipcode_home character varying,
    office_name character varying,
    address1_office character varying,
    address2_office character varying,
    subdistrict_office character varying,
    district_office character varying,
    provincecode_office character varying,
    zipcode_office character varying,
    forgotpasswordquestionid integer,
    forgotpasswordans character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ageoption ageoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ageoption
    ADD CONSTRAINT ageoption_pkey PRIMARY KEY (id);


--
-- Name: criteria criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criteria
    ADD CONSTRAINT criteria_pkey PRIMARY KEY (id);


--
-- Name: eduoption eduoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eduoption
    ADD CONSTRAINT eduoption_pkey PRIMARY KEY (id);


--
-- Name: forgotpasswordquestionoption forgotpasswordquestionoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forgotpasswordquestionoption
    ADD CONSTRAINT forgotpasswordquestionoption_pkey PRIMARY KEY (id);


--
-- Name: frechangenameoption frechangenameoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.frechangenameoption
    ADD CONSTRAINT frechangenameoption_pkey PRIMARY KEY (id);


--
-- Name: funcallow funcallow_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcallow
    ADD CONSTRAINT funcallow_pkey PRIMARY KEY (id);


--
-- Name: genderstatus genderstatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genderstatus
    ADD CONSTRAINT genderstatus_pkey PRIMARY KEY (id);


--
-- Name: geography geography_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.geography
    ADD CONSTRAINT geography_pkey PRIMARY KEY (id);


--
-- Name: haveguarantoroption haveguarantoroption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haveguarantoroption
    ADD CONSTRAINT haveguarantoroption_pkey PRIMARY KEY (id);


--
-- Name: iamguarantoroption iamguarantoroption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.iamguarantoroption
    ADD CONSTRAINT iamguarantoroption_pkey PRIMARY KEY (id);


--
-- Name: incomeperdebtoption incomeperdebtoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incomeperdebtoption
    ADD CONSTRAINT incomeperdebtoption_pkey PRIMARY KEY (id);


--
-- Name: incometrendoption incometrendoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incometrendoption
    ADD CONSTRAINT incometrendoption_pkey PRIMARY KEY (id);


--
-- Name: joboption joboption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.joboption
    ADD CONSTRAINT joboption_pkey PRIMARY KEY (id);


--
-- Name: loanobjectoption loanobjectoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loanobjectoption
    ADD CONSTRAINT loanobjectoption_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: marriedstatus marriedstatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marriedstatus
    ADD CONSTRAINT marriedstatus_pkey PRIMARY KEY (id);


--
-- Name: mortgagesecuritiesperloanoption mortgagesecuritiesperloanoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mortgagesecuritiesperloanoption
    ADD CONSTRAINT mortgagesecuritiesperloanoption_pkey PRIMARY KEY (id);


--
-- Name: paydebthistoryoption paydebthistoryoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paydebthistoryoption
    ADD CONSTRAINT paydebthistoryoption_pkey PRIMARY KEY (id);


--
-- Name: permissionaccess permissionaccess_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissionaccess
    ADD CONSTRAINT permissionaccess_pkey PRIMARY KEY (id);


--
-- Name: provinces provinces_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_pkey PRIMARY KEY (id);


--
-- Name: questionnaire questionnaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_pkey PRIMARY KEY (id);


--
-- Name: questionnairestatus questionnairestatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnairestatus
    ADD CONSTRAINT questionnairestatus_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: savingperloanoption savingperloanoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savingperloanoption
    ADD CONSTRAINT savingperloanoption_pkey PRIMARY KEY (id);


--
-- Name: statusinhouseparticularoption statusinhouseparticularoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statusinhouseparticularoption
    ADD CONSTRAINT statusinhouseparticularoption_pkey PRIMARY KEY (id);


--
-- Name: timejoboption timejoboption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timejoboption
    ADD CONSTRAINT timejoboption_pkey PRIMARY KEY (id);


--
-- Name: timeofnameinhouseparticularoption timeofnameinhouseparticularoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeofnameinhouseparticularoption
    ADD CONSTRAINT timeofnameinhouseparticularoption_pkey PRIMARY KEY (id);


--
-- Name: timeofphonenumberoption timeofphonenumberoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeofphonenumberoption
    ADD CONSTRAINT timeofphonenumberoption_pkey PRIMARY KEY (id);


--
-- Name: totaldebtperyearincomeoption totaldebtperyearincomeoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.totaldebtperyearincomeoption
    ADD CONSTRAINT totaldebtperyearincomeoption_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ageoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ageoption_code_idx ON public.ageoption USING btree (code);


--
-- Name: criteria_criteria_no_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX criteria_criteria_no_idx ON public.criteria USING btree (criteria_no);


--
-- Name: eduoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX eduoption_code_idx ON public.eduoption USING btree (code);


--
-- Name: frechangenameoption_code_asc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX frechangenameoption_code_asc ON public.frechangenameoption USING btree (code);


--
-- Name: frechangenameoption_code_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX frechangenameoption_code_id ON public.frechangenameoption USING btree (id);


--
-- Name: frechangenameoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX frechangenameoption_code_idx ON public.frechangenameoption USING btree (code);


--
-- Name: funcallow_funcno_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX funcallow_funcno_idx ON public.funcallow USING btree (funcno);


--
-- Name: haveguarantoroption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX haveguarantoroption_code_idx ON public.haveguarantoroption USING btree (code);


--
-- Name: iamguarantoroption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX iamguarantoroption_code_idx ON public.iamguarantoroption USING btree (code);


--
-- Name: incomeperdebtoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX incomeperdebtoption_code_idx ON public.incomeperdebtoption USING btree (code);


--
-- Name: incometrendoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX incometrendoption_code_idx ON public.incometrendoption USING btree (code);


--
-- Name: joboption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX joboption_code_idx ON public.joboption USING btree (code);


--
-- Name: loanobjectoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX loanobjectoption_code_idx ON public.loanobjectoption USING btree (code);


--
-- Name: mortgagesecuritiesperloanoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX mortgagesecuritiesperloanoption_code_idx ON public.mortgagesecuritiesperloanoption USING btree (code);


--
-- Name: paydebthistoryoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX paydebthistoryoption_code_idx ON public.paydebthistoryoption USING btree (code);


--
-- Name: province_code_inx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX province_code_inx ON public.provinces USING btree (code);


--
-- Name: questionnaire_loanerid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX questionnaire_loanerid_idx ON public.questionnaire USING btree (loanerid);


--
-- Name: questionnairestatus_id_asc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX questionnairestatus_id_asc ON public.questionnairestatus USING btree (id);


--
-- Name: savingperloanoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX savingperloanoption_code_idx ON public.savingperloanoption USING btree (code);


--
-- Name: statusinhouseparticularoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX statusinhouseparticularoption_code_idx ON public.statusinhouseparticularoption USING btree (code);


--
-- Name: timejoboption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX timejoboption_code_idx ON public.timejoboption USING btree (code);


--
-- Name: timeofnameinhouseparticularoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX timeofnameinhouseparticularoption_code_idx ON public.timeofnameinhouseparticularoption USING btree (code);


--
-- Name: timeofphonenumberoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX timeofphonenumberoption_code_idx ON public.timeofphonenumberoption USING btree (code);


--
-- Name: totaldebtperyearincomeoption_code_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX totaldebtperyearincomeoption_code_idx ON public.totaldebtperyearincomeoption USING btree (code);


--
-- Name: users_citizenid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_citizenid_idx ON public.users USING btree (citizenid);


--
-- Name: users_email_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_email_idx ON public.users USING btree (email);


--
-- Name: users_phone_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_phone_idx ON public.users USING btree (phone);


--
-- Name: ageoption ageoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ageoption
    ADD CONSTRAINT ageoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: eduoption eduoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eduoption
    ADD CONSTRAINT eduoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: frechangenameoption frechangenameoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.frechangenameoption
    ADD CONSTRAINT frechangenameoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: haveguarantoroption haveguarantoroption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haveguarantoroption
    ADD CONSTRAINT haveguarantoroption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: iamguarantoroption iamguarantoroption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.iamguarantoroption
    ADD CONSTRAINT iamguarantoroption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: incomeperdebtoption incomeperdebtoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incomeperdebtoption
    ADD CONSTRAINT incomeperdebtoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: incometrendoption incometrendoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incometrendoption
    ADD CONSTRAINT incometrendoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: joboption joboption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.joboption
    ADD CONSTRAINT joboption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: loanobjectoption loanobjectoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loanobjectoption
    ADD CONSTRAINT loanobjectoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: location location_province_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_province_code_fkey FOREIGN KEY (province_code) REFERENCES public.provinces(code);


--
-- Name: mortgagesecuritiesperloanoption mortgagesecuritiesperloanoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mortgagesecuritiesperloanoption
    ADD CONSTRAINT mortgagesecuritiesperloanoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: paydebthistoryoption paydebthistoryoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paydebthistoryoption
    ADD CONSTRAINT paydebthistoryoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: provinces provinces_geographyid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_geographyid_fkey FOREIGN KEY (geographyid) REFERENCES public.geography(id);


--
-- Name: questionnaire questionnaire_age_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_age_fkey FOREIGN KEY (age) REFERENCES public.ageoption(code);


--
-- Name: questionnaire questionnaire_agew_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_agew_fkey FOREIGN KEY (agew) REFERENCES public.ageoption(code);


--
-- Name: questionnaire questionnaire_edu_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_edu_fkey FOREIGN KEY (edu) REFERENCES public.eduoption(code);


--
-- Name: questionnaire questionnaire_eduw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_eduw_fkey FOREIGN KEY (eduw) REFERENCES public.eduoption(code);


--
-- Name: questionnaire questionnaire_frechangename_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_frechangename_fkey FOREIGN KEY (frechangename) REFERENCES public.frechangenameoption(code);


--
-- Name: questionnaire questionnaire_frechangenamew_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_frechangenamew_fkey FOREIGN KEY (frechangenamew) REFERENCES public.frechangenameoption(code);


--
-- Name: questionnaire questionnaire_haveguarantor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_haveguarantor_fkey FOREIGN KEY (haveguarantor) REFERENCES public.haveguarantoroption(code);


--
-- Name: questionnaire questionnaire_haveguarantorw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_haveguarantorw_fkey FOREIGN KEY (haveguarantorw) REFERENCES public.haveguarantoroption(code);


--
-- Name: questionnaire questionnaire_iamguarantor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_iamguarantor_fkey FOREIGN KEY (iamguarantor) REFERENCES public.iamguarantoroption(code);


--
-- Name: questionnaire questionnaire_iamguarantorw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_iamguarantorw_fkey FOREIGN KEY (iamguarantorw) REFERENCES public.iamguarantoroption(code);


--
-- Name: questionnaire questionnaire_incomeperdebt_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_incomeperdebt_fkey FOREIGN KEY (incomeperdebt) REFERENCES public.incomeperdebtoption(code);


--
-- Name: questionnaire questionnaire_incomeperdebtw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_incomeperdebtw_fkey FOREIGN KEY (incomeperdebtw) REFERENCES public.incomeperdebtoption(code);


--
-- Name: questionnaire questionnaire_incometrend_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_incometrend_fkey FOREIGN KEY (incometrend) REFERENCES public.incometrendoption(code);


--
-- Name: questionnaire questionnaire_incometrendw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_incometrendw_fkey FOREIGN KEY (incometrendw) REFERENCES public.incometrendoption(code);


--
-- Name: questionnaire questionnaire_job_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_job_fkey FOREIGN KEY (job) REFERENCES public.joboption(code);


--
-- Name: questionnaire questionnaire_jobw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_jobw_fkey FOREIGN KEY (jobw) REFERENCES public.joboption(code);


--
-- Name: questionnaire questionnaire_loanerid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_loanerid_fkey FOREIGN KEY (loanerid) REFERENCES public.users(id);


--
-- Name: questionnaire questionnaire_loanobject_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_loanobject_fkey FOREIGN KEY (loanobject) REFERENCES public.loanobjectoption(code);


--
-- Name: questionnaire questionnaire_loanobjectw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_loanobjectw_fkey FOREIGN KEY (loanobjectw) REFERENCES public.loanobjectoption(code);


--
-- Name: questionnaire questionnaire_mortgagesecuritiesperloan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_mortgagesecuritiesperloan_fkey FOREIGN KEY (mortgagesecuritiesperloan) REFERENCES public.mortgagesecuritiesperloanoption(code);


--
-- Name: questionnaire questionnaire_mortgagesecuritiesperloanw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_mortgagesecuritiesperloanw_fkey FOREIGN KEY (mortgagesecuritiesperloanw) REFERENCES public.mortgagesecuritiesperloanoption(code);


--
-- Name: questionnaire questionnaire_paydebthistory_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_paydebthistory_fkey FOREIGN KEY (paydebthistory) REFERENCES public.paydebthistoryoption(code);


--
-- Name: questionnaire questionnaire_paydebthistoryw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_paydebthistoryw_fkey FOREIGN KEY (paydebthistoryw) REFERENCES public.paydebthistoryoption(code);


--
-- Name: questionnaire questionnaire_provincecode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_provincecode_fkey FOREIGN KEY (provincecode) REFERENCES public.provinces(code);


--
-- Name: questionnaire questionnaire_provincecode_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_provincecode_fkey1 FOREIGN KEY (provincecode) REFERENCES public.provinces(code);


--
-- Name: questionnaire questionnaire_provincecodew_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_provincecodew_fkey FOREIGN KEY (provincecodew) REFERENCES public.provinces(code);


--
-- Name: questionnaire questionnaire_savingperloan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_savingperloan_fkey FOREIGN KEY (savingperloan) REFERENCES public.savingperloanoption(code);


--
-- Name: questionnaire questionnaire_savingperloanw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_savingperloanw_fkey FOREIGN KEY (savingperloanw) REFERENCES public.savingperloanoption(code);


--
-- Name: questionnaire questionnaire_statusid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_statusid_fkey FOREIGN KEY (statusid) REFERENCES public.questionnairestatus(id);


--
-- Name: questionnaire questionnaire_statusinhouseparticular_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_statusinhouseparticular_fkey FOREIGN KEY (statusinhouseparticular) REFERENCES public.statusinhouseparticularoption(code);


--
-- Name: questionnaire questionnaire_statusinhouseparticularw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_statusinhouseparticularw_fkey FOREIGN KEY (statusinhouseparticularw) REFERENCES public.statusinhouseparticularoption(code);


--
-- Name: questionnaire questionnaire_timejob_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timejob_fkey FOREIGN KEY (timejob) REFERENCES public.timejoboption(code);


--
-- Name: questionnaire questionnaire_timejobw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timejobw_fkey FOREIGN KEY (timejobw) REFERENCES public.timejoboption(code);


--
-- Name: questionnaire questionnaire_timeofnameinhouseparticular_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timeofnameinhouseparticular_fkey FOREIGN KEY (timeofnameinhouseparticular) REFERENCES public.timeofnameinhouseparticularoption(code);


--
-- Name: questionnaire questionnaire_timeofnameinhouseparticularw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timeofnameinhouseparticularw_fkey FOREIGN KEY (timeofnameinhouseparticularw) REFERENCES public.timeofnameinhouseparticularoption(code);


--
-- Name: questionnaire questionnaire_timeofphonenumber_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timeofphonenumber_fkey FOREIGN KEY (timeofphonenumber) REFERENCES public.timeofphonenumberoption(code);


--
-- Name: questionnaire questionnaire_timeofphonenumberw_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_timeofphonenumberw_fkey FOREIGN KEY (timeofphonenumberw) REFERENCES public.timeofphonenumberoption(code);


--
-- Name: questionnaire questionnaire_totaldebtperyearincome_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_totaldebtperyearincome_fkey FOREIGN KEY (totaldebtperyearincome) REFERENCES public.totaldebtperyearincomeoption(code);


--
-- Name: questionnaire questionnaire_totaldebtperyearincomew_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_totaldebtperyearincomew_fkey FOREIGN KEY (totaldebtperyearincomew) REFERENCES public.totaldebtperyearincomeoption(code);


--
-- Name: savingperloanoption savingperloanoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savingperloanoption
    ADD CONSTRAINT savingperloanoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: users sers_forgotpassowordquestionid_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT sers_forgotpassowordquestionid_fk FOREIGN KEY (forgotpasswordquestionid) REFERENCES public.forgotpasswordquestionoption(id);


--
-- Name: statusinhouseparticularoption statusinhouseparticularoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statusinhouseparticularoption
    ADD CONSTRAINT statusinhouseparticularoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: timejoboption timejoboption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timejoboption
    ADD CONSTRAINT timejoboption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: timeofnameinhouseparticularoption timeofnameinhouseparticularoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeofnameinhouseparticularoption
    ADD CONSTRAINT timeofnameinhouseparticularoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: timeofphonenumberoption timeofphonenumberoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeofphonenumberoption
    ADD CONSTRAINT timeofphonenumberoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: totaldebtperyearincomeoption totaldebtperyearincomeoption_criteria_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.totaldebtperyearincomeoption
    ADD CONSTRAINT totaldebtperyearincomeoption_criteria_no_fkey FOREIGN KEY (criteria_no) REFERENCES public.criteria(criteria_no);


--
-- Name: users users_genderid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_genderid_fkey FOREIGN KEY (genderid) REFERENCES public.genderstatus(id);


--
-- Name: users users_marriedid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_marriedid_fkey FOREIGN KEY (marriedid) REFERENCES public.marriedstatus(id);


--
-- Name: users users_provincecode_home_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_provincecode_home_fkey FOREIGN KEY (provincecode_home) REFERENCES public.provinces(code);


--
-- Name: users users_provincecode_office_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_provincecode_office_fkey FOREIGN KEY (provincecode_office) REFERENCES public.provinces(code);


--
-- Name: users users_roleid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_roleid_fkey FOREIGN KEY (roleid) REFERENCES public.roles(id);


--
-- PostgreSQL database dump complete
--

